name: macos

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        curl -sS https://raw.githubusercontent.com/averak/dotfiles/master/setup.sh | sh
