name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        ./scripts/install.sh
