name: ubuntu

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        /bin/bash -c "$(curl -sS https://raw.githubusercontent.com/averak/dotfiles/master/setup.sh)"
